package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Academia generated by hbm2java
 */
public class Academia implements java.io.Serializable {

	private Integer idAcademia;
	private Facultad facultad;
	private String nombreAcademia;
	private Integer idPresidente;
	private Integer idSecretario;
	private Set materias = new HashSet(0);

	public Academia() {
	}

	public Academia(Facultad facultad, String nombreAcademia, Integer idPresidente, Integer idSecretario,
			Set materias) {
		this.facultad = facultad;
		this.nombreAcademia = nombreAcademia;
		this.idPresidente = idPresidente;
		this.idSecretario = idSecretario;
		this.materias = materias;
	}

	public Integer getIdAcademia() {
		return this.idAcademia;
	}

	public void setIdAcademia(Integer idAcademia) {
		this.idAcademia = idAcademia;
	}

	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	public String getNombreAcademia() {
		return this.nombreAcademia;
	}

	public void setNombreAcademia(String nombreAcademia) {
		this.nombreAcademia = nombreAcademia;
	}

	public Integer getIdPresidente() {
		return this.idPresidente;
	}

	public void setIdPresidente(Integer idPresidente) {
		this.idPresidente = idPresidente;
	}

	public Integer getIdSecretario() {
		return this.idSecretario;
	}

	public void setIdSecretario(Integer idSecretario) {
		this.idSecretario = idSecretario;
	}

	public Set getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set materias) {
		this.materias = materias;
	}

}
