package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Acceso generated by hbm2java
 */
public class Acceso implements java.io.Serializable {

	private Integer idAcceso;
	private Docente docente;
	private String correo;
	private String pass;
	private String rol;
	private boolean estado;

	public Acceso() {
	}

	public Acceso(Docente docente, String pass, String rol, boolean estado) {
		this.docente = docente;
		this.pass = pass;
		this.rol = rol;
		this.estado = estado;
	}

	public Acceso(Docente docente, String correo, String pass, String rol, boolean estado) {
		this.docente = docente;
		this.correo = correo;
		this.pass = pass;
		this.rol = rol;
		this.estado = estado;
	}

	public Integer getIdAcceso() {
		return this.idAcceso;
	}

	public void setIdAcceso(Integer idAcceso) {
		this.idAcceso = idAcceso;
	}

	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
