package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Actividaddoc generated by hbm2java
 */
public class Actividaddoc implements java.io.Serializable {

	private Integer idActividadDocente;
	private Subcompetencia subcompetencia;
	private String actividadDocente;
	private String rolActividad;

	public Actividaddoc() {
	}

	public Actividaddoc(Subcompetencia subcompetencia, String actividadDocente, String rolActividad) {
		this.subcompetencia = subcompetencia;
		this.actividadDocente = actividadDocente;
		this.rolActividad = rolActividad;
	}

	public Integer getIdActividadDocente() {
		return this.idActividadDocente;
	}

	public void setIdActividadDocente(Integer idActividadDocente) {
		this.idActividadDocente = idActividadDocente;
	}

	public Subcompetencia getSubcompetencia() {
		return this.subcompetencia;
	}

	public void setSubcompetencia(Subcompetencia subcompetencia) {
		this.subcompetencia = subcompetencia;
	}

	public String getActividadDocente() {
		return this.actividadDocente;
	}

	public void setActividadDocente(String actividadDocente) {
		this.actividadDocente = actividadDocente;
	}

	public String getRolActividad() {
		return this.rolActividad;
	}

	public void setRolActividad(String rolActividad) {
		this.rolActividad = rolActividad;
	}

}
