package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Actividadal generated by hbm2java
 */
public class Actividadal implements java.io.Serializable {

	private Integer idActividadAlumno;
	private Subcompetencia subcompetencia;
	private String actividadAlumno;
	private String rolActividad;

	public Actividadal() {
	}

	public Actividadal(Subcompetencia subcompetencia, String actividadAlumno, String rolActividad) {
		this.subcompetencia = subcompetencia;
		this.actividadAlumno = actividadAlumno;
		this.rolActividad = rolActividad;
	}

	public Integer getIdActividadAlumno() {
		return this.idActividadAlumno;
	}

	public void setIdActividadAlumno(Integer idActividadAlumno) {
		this.idActividadAlumno = idActividadAlumno;
	}

	public Subcompetencia getSubcompetencia() {
		return this.subcompetencia;
	}

	public void setSubcompetencia(Subcompetencia subcompetencia) {
		this.subcompetencia = subcompetencia;
	}

	public String getActividadAlumno() {
		return this.actividadAlumno;
	}

	public void setActividadAlumno(String actividadAlumno) {
		this.actividadAlumno = actividadAlumno;
	}

	public String getRolActividad() {
		return this.rolActividad;
	}

	public void setRolActividad(String rolActividad) {
		this.rolActividad = rolActividad;
	}

}
