package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ambiente generated by hbm2java
 */
public class Ambiente implements java.io.Serializable {

	private Integer idAmbiente;
	private String ambiente;
	private Set subcompetenciaAmbientes = new HashSet(0);

	public Ambiente() {
	}

	public Ambiente(String ambiente, Set subcompetenciaAmbientes) {
		this.ambiente = ambiente;
		this.subcompetenciaAmbientes = subcompetenciaAmbientes;
	}

	public Integer getIdAmbiente() {
		return this.idAmbiente;
	}

	public void setIdAmbiente(Integer idAmbiente) {
		this.idAmbiente = idAmbiente;
	}

	public String getAmbiente() {
		return this.ambiente;
	}

	public void setAmbiente(String ambiente) {
		this.ambiente = ambiente;
	}

	public Set getSubcompetenciaAmbientes() {
		return this.subcompetenciaAmbientes;
	}

	public void setSubcompetenciaAmbientes(Set subcompetenciaAmbientes) {
		this.subcompetenciaAmbientes = subcompetenciaAmbientes;
	}

}
