package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Aream generated by hbm2java
 */
public class Aream implements java.io.Serializable {

	private Integer idArea;
	private String area;
	private Set materias = new HashSet(0);

	public Aream() {
	}

	public Aream(String area, Set materias) {
		this.area = area;
		this.materias = materias;
	}

	public Integer getIdArea() {
		return this.idArea;
	}

	public void setIdArea(Integer idArea) {
		this.idArea = idArea;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public Set getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set materias) {
		this.materias = materias;
	}

}
