package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * BibliografiaPua generated by hbm2java
 */
public class BibliografiaPua implements java.io.Serializable {

	private BibliografiaPuaId id;
	private Libro libro;
	private Pua pua;
	private Tipobib tipobib;

	public BibliografiaPua() {
	}

	public BibliografiaPua(BibliografiaPuaId id) {
		this.id = id;
	}

	public BibliografiaPua(BibliografiaPuaId id, Libro libro, Pua pua, Tipobib tipobib) {
		this.id = id;
		this.libro = libro;
		this.pua = pua;
		this.tipobib = tipobib;
	}

	public BibliografiaPuaId getId() {
		return this.id;
	}

	public void setId(BibliografiaPuaId id) {
		this.id = id;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public Pua getPua() {
		return this.pua;
	}

	public void setPua(Pua pua) {
		this.pua = pua;
	}

	public Tipobib getTipobib() {
		return this.tipobib;
	}

	public void setTipobib(Tipobib tipobib) {
		this.tipobib = tipobib;
	}

}
