package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * BibliografiaPuaId generated by hbm2java
 */
public class BibliografiaPuaId implements java.io.Serializable {

	private Integer idPua;
	private Integer idLibro;
	private Integer idTipoBibliografia;

	public BibliografiaPuaId() {
	}

	public BibliografiaPuaId(Integer idPua, Integer idLibro, Integer idTipoBibliografia) {
		this.idPua = idPua;
		this.idLibro = idLibro;
		this.idTipoBibliografia = idTipoBibliografia;
	}

	public Integer getIdPua() {
		return this.idPua;
	}

	public void setIdPua(Integer idPua) {
		this.idPua = idPua;
	}

	public Integer getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(Integer idLibro) {
		this.idLibro = idLibro;
	}

	public Integer getIdTipoBibliografia() {
		return this.idTipoBibliografia;
	}

	public void setIdTipoBibliografia(Integer idTipoBibliografia) {
		this.idTipoBibliografia = idTipoBibliografia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BibliografiaPuaId))
			return false;
		BibliografiaPuaId castOther = (BibliografiaPuaId) other;

		return ((this.getIdPua() == castOther.getIdPua()) || (this.getIdPua() != null && castOther.getIdPua() != null
				&& this.getIdPua().equals(castOther.getIdPua())))
				&& ((this.getIdLibro() == castOther.getIdLibro()) || (this.getIdLibro() != null
						&& castOther.getIdLibro() != null && this.getIdLibro().equals(castOther.getIdLibro())))
				&& ((this.getIdTipoBibliografia() == castOther.getIdTipoBibliografia())
						|| (this.getIdTipoBibliografia() != null && castOther.getIdTipoBibliografia() != null
								&& this.getIdTipoBibliografia().equals(castOther.getIdTipoBibliografia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdPua() == null ? 0 : this.getIdPua().hashCode());
		result = 37 * result + (getIdLibro() == null ? 0 : this.getIdLibro().hashCode());
		result = 37 * result + (getIdTipoBibliografia() == null ? 0 : this.getIdTipoBibliografia().hashCode());
		return result;
	}

}
