package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * BibliografiaSubcompetencia generated by hbm2java
 */
public class BibliografiaSubcompetencia implements java.io.Serializable {

	private BibliografiaSubcompetenciaId id;
	private Libro libro;
	private Subcompetencia subcompetencia;

	public BibliografiaSubcompetencia() {
	}

	public BibliografiaSubcompetencia(BibliografiaSubcompetenciaId id) {
		this.id = id;
	}

	public BibliografiaSubcompetencia(BibliografiaSubcompetenciaId id, Libro libro, Subcompetencia subcompetencia) {
		this.id = id;
		this.libro = libro;
		this.subcompetencia = subcompetencia;
	}

	public BibliografiaSubcompetenciaId getId() {
		return this.id;
	}

	public void setId(BibliografiaSubcompetenciaId id) {
		this.id = id;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public Subcompetencia getSubcompetencia() {
		return this.subcompetencia;
	}

	public void setSubcompetencia(Subcompetencia subcompetencia) {
		this.subcompetencia = subcompetencia;
	}

}
