package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera implements java.io.Serializable {

	private Integer idCarrera;
	private Facultad facultad;
	private String nombreCarrera;
	private Integer planEstudios;
	private Integer idCoordinador;
	private Set competenciaesps = new HashSet(0);
	private Set materias = new HashSet(0);

	public Carrera() {
	}

	public Carrera(Facultad facultad, String nombreCarrera, Integer planEstudios, Integer idCoordinador,
			Set competenciaesps, Set materias) {
		this.facultad = facultad;
		this.nombreCarrera = nombreCarrera;
		this.planEstudios = planEstudios;
		this.idCoordinador = idCoordinador;
		this.competenciaesps = competenciaesps;
		this.materias = materias;
	}

	public Integer getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(Integer idCarrera) {
		this.idCarrera = idCarrera;
	}

	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	public String getNombreCarrera() {
		return this.nombreCarrera;
	}

	public void setNombreCarrera(String nombreCarrera) {
		this.nombreCarrera = nombreCarrera;
	}

	public Integer getPlanEstudios() {
		return this.planEstudios;
	}

	public void setPlanEstudios(Integer planEstudios) {
		this.planEstudios = planEstudios;
	}

	public Integer getIdCoordinador() {
		return this.idCoordinador;
	}

	public void setIdCoordinador(Integer idCoordinador) {
		this.idCoordinador = idCoordinador;
	}

	public Set getCompetenciaesps() {
		return this.competenciaesps;
	}

	public void setCompetenciaesps(Set competenciaesps) {
		this.competenciaesps = competenciaesps;
	}

	public Set getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set materias) {
		this.materias = materias;
	}

}
