package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Competenciaesp generated by hbm2java
 */
public class Competenciaesp implements java.io.Serializable {

	private Integer idEspecifica;
	private Carrera carrera;
	private String competenciaEspecifica;
	private Set puas = new HashSet(0);

	public Competenciaesp() {
	}

	public Competenciaesp(Carrera carrera, String competenciaEspecifica, Set puas) {
		this.carrera = carrera;
		this.competenciaEspecifica = competenciaEspecifica;
		this.puas = puas;
	}

	public Integer getIdEspecifica() {
		return this.idEspecifica;
	}

	public void setIdEspecifica(Integer idEspecifica) {
		this.idEspecifica = idEspecifica;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public String getCompetenciaEspecifica() {
		return this.competenciaEspecifica;
	}

	public void setCompetenciaEspecifica(String competenciaEspecifica) {
		this.competenciaEspecifica = competenciaEspecifica;
	}

	public Set getPuas() {
		return this.puas;
	}

	public void setPuas(Set puas) {
		this.puas = puas;
	}

}
