package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Competenciagen generated by hbm2java
 */
public class Competenciagen implements java.io.Serializable {

	private Integer idGenerica;
	private String competenciaGenerica;
	private Set puas = new HashSet(0);

	public Competenciagen() {
	}

	public Competenciagen(String competenciaGenerica, Set puas) {
		this.competenciaGenerica = competenciaGenerica;
		this.puas = puas;
	}

	public Integer getIdGenerica() {
		return this.idGenerica;
	}

	public void setIdGenerica(Integer idGenerica) {
		this.idGenerica = idGenerica;
	}

	public String getCompetenciaGenerica() {
		return this.competenciaGenerica;
	}

	public void setCompetenciaGenerica(String competenciaGenerica) {
		this.competenciaGenerica = competenciaGenerica;
	}

	public Set getPuas() {
		return this.puas;
	}

	public void setPuas(Set puas) {
		this.puas = puas;
	}

}
