package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Criterio generated by hbm2java
 */
public class Criterio implements java.io.Serializable {

	private Integer idCriterio;
	private Subcompetencia subcompetencia;
	private String criterio;

	public Criterio() {
	}

	public Criterio(Subcompetencia subcompetencia, String criterio) {
		this.subcompetencia = subcompetencia;
		this.criterio = criterio;
	}

	public Integer getIdCriterio() {
		return this.idCriterio;
	}

	public void setIdCriterio(Integer idCriterio) {
		this.idCriterio = idCriterio;
	}

	public Subcompetencia getSubcompetencia() {
		return this.subcompetencia;
	}

	public void setSubcompetencia(Subcompetencia subcompetencia) {
		this.subcompetencia = subcompetencia;
	}

	public String getCriterio() {
		return this.criterio;
	}

	public void setCriterio(String criterio) {
		this.criterio = criterio;
	}

}
