package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente implements java.io.Serializable {

	private Integer idDocente;
	private String prefijo;
	private String nombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String correo;
	private Set puas = new HashSet(0);
	private Set materias = new HashSet(0);
	private Set facultads = new HashSet(0);
	private Set accesos = new HashSet(0);

	public Docente() {
	}

	public Docente(String prefijo, String nombre, String apellidoPaterno, String apellidoMaterno, String correo,
			Set puas, Set materias, Set facultads, Set accesos) {
		this.prefijo = prefijo;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.correo = correo;
		this.puas = puas;
		this.materias = materias;
		this.facultads = facultads;
		this.accesos = accesos;
	}

	public Integer getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(Integer idDocente) {
		this.idDocente = idDocente;
	}

	public String getPrefijo() {
		return this.prefijo;
	}

	public void setPrefijo(String prefijo) {
		this.prefijo = prefijo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Set getPuas() {
		return this.puas;
	}

	public void setPuas(Set puas) {
		this.puas = puas;
	}

	public Set getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set materias) {
		this.materias = materias;
	}

	public Set getFacultads() {
		return this.facultads;
	}

	public void setFacultads(Set facultads) {
		this.facultads = facultads;
	}

	public Set getAccesos() {
		return this.accesos;
	}

	public void setAccesos(Set accesos) {
		this.accesos = accesos;
	}

}
