package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Editorial generated by hbm2java
 */
public class Editorial implements java.io.Serializable {

	private Integer idEditorial;
	private String editorial;
	private Set libros = new HashSet(0);

	public Editorial() {
	}

	public Editorial(String editorial) {
		this.editorial = editorial;
	}

	public Editorial(String editorial, Set libros) {
		this.editorial = editorial;
		this.libros = libros;
	}

	public Integer getIdEditorial() {
		return this.idEditorial;
	}

	public void setIdEditorial(Integer idEditorial) {
		this.idEditorial = idEditorial;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public Set getLibros() {
		return this.libros;
	}

	public void setLibros(Set libros) {
		this.libros = libros;
	}

}
