package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * EvaluacionCompetencias generated by hbm2java
 */
public class EvaluacionCompetencias implements java.io.Serializable {

	private Integer idEvaluacionCompetencias;
	private Pua pua;
	private String evaluacionFinal;
	private Integer ponderacion;

	public EvaluacionCompetencias() {
	}

	public EvaluacionCompetencias(Pua pua, String evaluacionFinal, Integer ponderacion) {
		this.pua = pua;
		this.evaluacionFinal = evaluacionFinal;
		this.ponderacion = ponderacion;
	}

	public Integer getIdEvaluacionCompetencias() {
		return this.idEvaluacionCompetencias;
	}

	public void setIdEvaluacionCompetencias(Integer idEvaluacionCompetencias) {
		this.idEvaluacionCompetencias = idEvaluacionCompetencias;
	}

	public Pua getPua() {
		return this.pua;
	}

	public void setPua(Pua pua) {
		this.pua = pua;
	}

	public String getEvaluacionFinal() {
		return this.evaluacionFinal;
	}

	public void setEvaluacionFinal(String evaluacionFinal) {
		this.evaluacionFinal = evaluacionFinal;
	}

	public Integer getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(Integer ponderacion) {
		this.ponderacion = ponderacion;
	}

}
