package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * EvidenciaSubcompetenciaId generated by hbm2java
 */
public class EvidenciaSubcompetenciaId implements java.io.Serializable {

	private Integer idSubcompetencia;
	private Integer idEvidencia;
	private Integer ponderacion;

	public EvidenciaSubcompetenciaId() {
	}

	public EvidenciaSubcompetenciaId(Integer idSubcompetencia, Integer idEvidencia, Integer ponderacion) {
		this.idSubcompetencia = idSubcompetencia;
		this.idEvidencia = idEvidencia;
		this.ponderacion = ponderacion;
	}

	public Integer getIdSubcompetencia() {
		return this.idSubcompetencia;
	}

	public void setIdSubcompetencia(Integer idSubcompetencia) {
		this.idSubcompetencia = idSubcompetencia;
	}

	public Integer getIdEvidencia() {
		return this.idEvidencia;
	}

	public void setIdEvidencia(Integer idEvidencia) {
		this.idEvidencia = idEvidencia;
	}

	public Integer getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(Integer ponderacion) {
		this.ponderacion = ponderacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EvidenciaSubcompetenciaId))
			return false;
		EvidenciaSubcompetenciaId castOther = (EvidenciaSubcompetenciaId) other;

		return ((this.getIdSubcompetencia() == castOther.getIdSubcompetencia())
				|| (this.getIdSubcompetencia() != null && castOther.getIdSubcompetencia() != null
						&& this.getIdSubcompetencia().equals(castOther.getIdSubcompetencia())))
				&& ((this.getIdEvidencia() == castOther.getIdEvidencia())
						|| (this.getIdEvidencia() != null && castOther.getIdEvidencia() != null
								&& this.getIdEvidencia().equals(castOther.getIdEvidencia())))
				&& ((this.getPonderacion() == castOther.getPonderacion())
						|| (this.getPonderacion() != null && castOther.getPonderacion() != null
								&& this.getPonderacion().equals(castOther.getPonderacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSubcompetencia() == null ? 0 : this.getIdSubcompetencia().hashCode());
		result = 37 * result + (getIdEvidencia() == null ? 0 : this.getIdEvidencia().hashCode());
		result = 37 * result + (getPonderacion() == null ? 0 : this.getPonderacion().hashCode());
		return result;
	}

}
