package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * EvidenciaSubcompetencia generated by hbm2java
 */
public class EvidenciaSubcompetencia implements java.io.Serializable {

	private EvidenciaSubcompetenciaId id;
	private Evidencia evidencia;
	private Subcompetencia subcompetencia;

	public EvidenciaSubcompetencia() {
	}

	public EvidenciaSubcompetencia(EvidenciaSubcompetenciaId id) {
		this.id = id;
	}

	public EvidenciaSubcompetencia(EvidenciaSubcompetenciaId id, Evidencia evidencia, Subcompetencia subcompetencia) {
		this.id = id;
		this.evidencia = evidencia;
		this.subcompetencia = subcompetencia;
	}

	public EvidenciaSubcompetenciaId getId() {
		return this.id;
	}

	public void setId(EvidenciaSubcompetenciaId id) {
		this.id = id;
	}

	public Evidencia getEvidencia() {
		return this.evidencia;
	}

	public void setEvidencia(Evidencia evidencia) {
		this.evidencia = evidencia;
	}

	public Subcompetencia getSubcompetencia() {
		return this.subcompetencia;
	}

	public void setSubcompetencia(Subcompetencia subcompetencia) {
		this.subcompetencia = subcompetencia;
	}

}
