package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Evidencia generated by hbm2java
 */
public class Evidencia implements java.io.Serializable {

	private int idEvidencia;
	private String evidencia;
	private Set evidenciaSubcompetencias = new HashSet(0);

	public Evidencia() {
	}

	public Evidencia(int idEvidencia) {
		this.idEvidencia = idEvidencia;
	}

	public Evidencia(int idEvidencia, String evidencia, Set evidenciaSubcompetencias) {
		this.idEvidencia = idEvidencia;
		this.evidencia = evidencia;
		this.evidenciaSubcompetencias = evidenciaSubcompetencias;
	}

	public int getIdEvidencia() {
		return this.idEvidencia;
	}

	public void setIdEvidencia(int idEvidencia) {
		this.idEvidencia = idEvidencia;
	}

	public String getEvidencia() {
		return this.evidencia;
	}

	public void setEvidencia(String evidencia) {
		this.evidencia = evidencia;
	}

	public Set getEvidenciaSubcompetencias() {
		return this.evidenciaSubcompetencias;
	}

	public void setEvidenciaSubcompetencias(Set evidenciaSubcompetencias) {
		this.evidenciaSubcompetencias = evidenciaSubcompetencias;
	}

}
