package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Facultad generated by hbm2java
 */
public class Facultad implements java.io.Serializable {

	private Integer idFacultad;
	private String facultad;
	private Integer idDirector;
	private Integer idSecretarioAcademico;
	private String micrositio;
	private Set docentes = new HashSet(0);
	private Set academias = new HashSet(0);
	private Set carreras = new HashSet(0);

	public Facultad() {
	}

	public Facultad(String facultad, Integer idDirector, Integer idSecretarioAcademico, String micrositio, Set docentes,
			Set academias, Set carreras) {
		this.facultad = facultad;
		this.idDirector = idDirector;
		this.idSecretarioAcademico = idSecretarioAcademico;
		this.micrositio = micrositio;
		this.docentes = docentes;
		this.academias = academias;
		this.carreras = carreras;
	}

	public Integer getIdFacultad() {
		return this.idFacultad;
	}

	public void setIdFacultad(Integer idFacultad) {
		this.idFacultad = idFacultad;
	}

	public String getFacultad() {
		return this.facultad;
	}

	public void setFacultad(String facultad) {
		this.facultad = facultad;
	}

	public Integer getIdDirector() {
		return this.idDirector;
	}

	public void setIdDirector(Integer idDirector) {
		this.idDirector = idDirector;
	}

	public Integer getIdSecretarioAcademico() {
		return this.idSecretarioAcademico;
	}

	public void setIdSecretarioAcademico(Integer idSecretarioAcademico) {
		this.idSecretarioAcademico = idSecretarioAcademico;
	}

	public String getMicrositio() {
		return this.micrositio;
	}

	public void setMicrositio(String micrositio) {
		this.micrositio = micrositio;
	}

	public Set getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set docentes) {
		this.docentes = docentes;
	}

	public Set getAcademias() {
		return this.academias;
	}

	public void setAcademias(Set academias) {
		this.academias = academias;
	}

	public Set getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set carreras) {
		this.carreras = carreras;
	}

}
