package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private Integer idLibro;
	private Editorial editorial;
	private String libro;
	private String autorPrincipal;
	private Set bibliografiaPuas = new HashSet(0);
	private Set bibliografiaSubcompetencias = new HashSet(0);

	public Libro() {
	}

	public Libro(Editorial editorial) {
		this.editorial = editorial;
	}

	public Libro(Editorial editorial, String libro, String autorPrincipal, Set bibliografiaPuas,
			Set bibliografiaSubcompetencias) {
		this.editorial = editorial;
		this.libro = libro;
		this.autorPrincipal = autorPrincipal;
		this.bibliografiaPuas = bibliografiaPuas;
		this.bibliografiaSubcompetencias = bibliografiaSubcompetencias;
	}

	public Integer getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(Integer idLibro) {
		this.idLibro = idLibro;
	}

	public Editorial getEditorial() {
		return this.editorial;
	}

	public void setEditorial(Editorial editorial) {
		this.editorial = editorial;
	}

	public String getLibro() {
		return this.libro;
	}

	public void setLibro(String libro) {
		this.libro = libro;
	}

	public String getAutorPrincipal() {
		return this.autorPrincipal;
	}

	public void setAutorPrincipal(String autorPrincipal) {
		this.autorPrincipal = autorPrincipal;
	}

	public Set getBibliografiaPuas() {
		return this.bibliografiaPuas;
	}

	public void setBibliografiaPuas(Set bibliografiaPuas) {
		this.bibliografiaPuas = bibliografiaPuas;
	}

	public Set getBibliografiaSubcompetencias() {
		return this.bibliografiaSubcompetencias;
	}

	public void setBibliografiaSubcompetencias(Set bibliografiaSubcompetencias) {
		this.bibliografiaSubcompetencias = bibliografiaSubcompetencias;
	}

}
