package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia implements java.io.Serializable {

	private Integer idMateria;
	private Aream aream;
	private Nucleom nucleom;
	private Tipom tipom;
	private String nombreMateria;
	private Integer creditosTotales;
	private Integer horasTotales;
	private Integer horasTeoricas;
	private Integer horasPracticas;
	private String art57;
	private Set academias = new HashSet(0);
	private Set carreras = new HashSet(0);
	private Set docentes = new HashSet(0);
	private Set puas = new HashSet(0);

	public Materia() {
	}

	public Materia(Aream aream, Nucleom nucleom, Tipom tipom, String nombreMateria, Integer creditosTotales,
			Integer horasTotales, Integer horasTeoricas, Integer horasPracticas, String art57, Set academias,
			Set carreras, Set docentes, Set puas) {
		this.aream = aream;
		this.nucleom = nucleom;
		this.tipom = tipom;
		this.nombreMateria = nombreMateria;
		this.creditosTotales = creditosTotales;
		this.horasTotales = horasTotales;
		this.horasTeoricas = horasTeoricas;
		this.horasPracticas = horasPracticas;
		this.art57 = art57;
		this.academias = academias;
		this.carreras = carreras;
		this.docentes = docentes;
		this.puas = puas;
	}

	public Integer getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(Integer idMateria) {
		this.idMateria = idMateria;
	}

	public Aream getAream() {
		return this.aream;
	}

	public void setAream(Aream aream) {
		this.aream = aream;
	}

	public Nucleom getNucleom() {
		return this.nucleom;
	}

	public void setNucleom(Nucleom nucleom) {
		this.nucleom = nucleom;
	}

	public Tipom getTipom() {
		return this.tipom;
	}

	public void setTipom(Tipom tipom) {
		this.tipom = tipom;
	}

	public String getNombreMateria() {
		return this.nombreMateria;
	}

	public void setNombreMateria(String nombreMateria) {
		this.nombreMateria = nombreMateria;
	}

	public Integer getCreditosTotales() {
		return this.creditosTotales;
	}

	public void setCreditosTotales(Integer creditosTotales) {
		this.creditosTotales = creditosTotales;
	}

	public Integer getHorasTotales() {
		return this.horasTotales;
	}

	public void setHorasTotales(Integer horasTotales) {
		this.horasTotales = horasTotales;
	}

	public Integer getHorasTeoricas() {
		return this.horasTeoricas;
	}

	public void setHorasTeoricas(Integer horasTeoricas) {
		this.horasTeoricas = horasTeoricas;
	}

	public Integer getHorasPracticas() {
		return this.horasPracticas;
	}

	public void setHorasPracticas(Integer horasPracticas) {
		this.horasPracticas = horasPracticas;
	}

	public String getArt57() {
		return this.art57;
	}

	public void setArt57(String art57) {
		this.art57 = art57;
	}

	public Set getAcademias() {
		return this.academias;
	}

	public void setAcademias(Set academias) {
		this.academias = academias;
	}

	public Set getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set carreras) {
		this.carreras = carreras;
	}

	public Set getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set docentes) {
		this.docentes = docentes;
	}

	public Set getPuas() {
		return this.puas;
	}

	public void setPuas(Set puas) {
		this.puas = puas;
	}

}
