package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material implements java.io.Serializable {

	private Integer idMaterial;
	private String material;
	private Set subcompetenciaMaterials = new HashSet(0);

	public Material() {
	}

	public Material(String material, Set subcompetenciaMaterials) {
		this.material = material;
		this.subcompetenciaMaterials = subcompetenciaMaterials;
	}

	public Integer getIdMaterial() {
		return this.idMaterial;
	}

	public void setIdMaterial(Integer idMaterial) {
		this.idMaterial = idMaterial;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public Set getSubcompetenciaMaterials() {
		return this.subcompetenciaMaterials;
	}

	public void setSubcompetenciaMaterials(Set subcompetenciaMaterials) {
		this.subcompetenciaMaterials = subcompetenciaMaterials;
	}

}
