package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Nucleom generated by hbm2java
 */
public class Nucleom implements java.io.Serializable {

	private Integer idNucleo;
	private String nucleo;
	private Set materias = new HashSet(0);

	public Nucleom() {
	}

	public Nucleom(String nucleo, Set materias) {
		this.nucleo = nucleo;
		this.materias = materias;
	}

	public Integer getIdNucleo() {
		return this.idNucleo;
	}

	public void setIdNucleo(Integer idNucleo) {
		this.idNucleo = idNucleo;
	}

	public String getNucleo() {
		return this.nucleo;
	}

	public void setNucleo(String nucleo) {
		this.nucleo = nucleo;
	}

	public Set getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set materias) {
		this.materias = materias;
	}

}
