package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Perfilprof generated by hbm2java
 */
public class Perfilprof implements java.io.Serializable {

	private Integer idPerfilProf;
	private Pua pua;
	private String perfilProf;

	public Perfilprof() {
	}

	public Perfilprof(Pua pua, String perfilProf) {
		this.pua = pua;
		this.perfilProf = perfilProf;
	}

	public Integer getIdPerfilProf() {
		return this.idPerfilProf;
	}

	public void setIdPerfilProf(Integer idPerfilProf) {
		this.idPerfilProf = idPerfilProf;
	}

	public Pua getPua() {
		return this.pua;
	}

	public void setPua(Pua pua) {
		this.pua = pua;
	}

	public String getPerfilProf() {
		return this.perfilProf;
	}

	public void setPerfilProf(String perfilProf) {
		this.perfilProf = perfilProf;
	}

}
