package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Perfildoc generated by hbm2java
 */
public class Perfildoc implements java.io.Serializable {

	private Integer idPerfilDoc;
	private Pua pua;
	private String perfilDoc;

	public Perfildoc() {
	}

	public Perfildoc(Pua pua, String perfilDoc) {
		this.pua = pua;
		this.perfilDoc = perfilDoc;
	}

	public Integer getIdPerfilDoc() {
		return this.idPerfilDoc;
	}

	public void setIdPerfilDoc(Integer idPerfilDoc) {
		this.idPerfilDoc = idPerfilDoc;
	}

	public Pua getPua() {
		return this.pua;
	}

	public void setPua(Pua pua) {
		this.pua = pua;
	}

	public String getPerfilDoc() {
		return this.perfilDoc;
	}

	public void setPerfilDoc(String perfilDoc) {
		this.perfilDoc = perfilDoc;
	}

}
