package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Perfilacad generated by hbm2java
 */
public class Perfilacad implements java.io.Serializable {

	private Integer idPerfilAcad;
	private Pua pua;
	private String perfilAcad;

	public Perfilacad() {
	}

	public Perfilacad(Pua pua, String perfilAcad) {
		this.pua = pua;
		this.perfilAcad = perfilAcad;
	}

	public Integer getIdPerfilAcad() {
		return this.idPerfilAcad;
	}

	public void setIdPerfilAcad(Integer idPerfilAcad) {
		this.idPerfilAcad = idPerfilAcad;
	}

	public Pua getPua() {
		return this.pua;
	}

	public void setPua(Pua pua) {
		this.pua = pua;
	}

	public String getPerfilAcad() {
		return this.perfilAcad;
	}

	public void setPerfilAcad(String perfilAcad) {
		this.perfilAcad = perfilAcad;
	}

}
