package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pua generated by hbm2java
 */
public class Pua implements java.io.Serializable {

	private Integer idPua;
	private Materia materia;
	private Integer acreditacionCompetencias;
	private String competenciaUda;
	private String competenciaFormacion;
	private int planEstudio;
	private boolean estado;
	private boolean autorizado;
	private Set docentes = new HashSet(0);
    private Set competenciaesps = new HashSet(0);
    private Set perfilprofs = new HashSet(0);
    private Set puaVersions = new HashSet(0);
    private Set subcompetencias = new HashSet(0);
    private Set evaluacionCompetenciases = new HashSet(0);
    private Set perfildocs = new HashSet(0);
    private Set evaluacionFinals = new HashSet(0);
    private Set perfilacads = new HashSet(0);
    private Set competenciagens = new HashSet(0);

   public Pua() {
   }

	
   public Pua(int planEstudio, boolean estado) {
       this.planEstudio = planEstudio;
       this.estado = estado;
   }
   public Pua(Materia materia, Integer acreditacionCompetencias, String competenciaUda, String competenciaFormacion, int planEstudio, boolean estado, boolean autorizado, Set docentes, Set competenciaesps, Set perfilprofs, Set puaVersions, Set subcompetencias, Set evaluacionCompetenciases, Set perfildocs, Set evaluacionFinals, Set perfilacads, Set competenciagens) {
      this.materia = materia;
      this.acreditacionCompetencias = acreditacionCompetencias;
      this.competenciaUda = competenciaUda;
      this.competenciaFormacion = competenciaFormacion;
      this.planEstudio = planEstudio;
      this.estado = estado;
      this.docentes = docentes;
      this.competenciaesps = competenciaesps;
      this.perfilprofs = perfilprofs;
      this.puaVersions = puaVersions;
      this.subcompetencias = subcompetencias;
      this.evaluacionCompetenciases = evaluacionCompetenciases;
      this.perfildocs = perfildocs;
      this.evaluacionFinals = evaluacionFinals;
      this.perfilacads = perfilacads;
      this.competenciagens = competenciagens;
      this.autorizado=autorizado;
   }
  
   public boolean isAutorizado() {
	   return autorizado;
	}
	
	
	public void setAutorizado(boolean autorizado) {
		this.autorizado = autorizado;
	}


public Integer getIdPua() {
       return this.idPua;
   }
   
   public void setIdPua(Integer idPua) {
       this.idPua = idPua;
   }
   public Materia getMateria() {
       return this.materia;
   }
   
   public void setMateria(Materia materia) {
       this.materia = materia;
   }
   public Integer getAcreditacionCompetencias() {
       return this.acreditacionCompetencias;
   }
   
   public void setAcreditacionCompetencias(Integer acreditacionCompetencias) {
       this.acreditacionCompetencias = acreditacionCompetencias;
   }
   public String getCompetenciaUda() {
       return this.competenciaUda;
   }
   
   public void setCompetenciaUda(String competenciaUda) {
       this.competenciaUda = competenciaUda;
   }
   public String getCompetenciaFormacion() {
       return this.competenciaFormacion;
   }
   
   public void setCompetenciaFormacion(String competenciaFormacion) {
       this.competenciaFormacion = competenciaFormacion;
   }
   public int getPlanEstudio() {
       return this.planEstudio;
   }
   
   public void setPlanEstudio(int planEstudio) {
       this.planEstudio = planEstudio;
   }
   public boolean isEstado() {
       return this.estado;
   }
   
   public void setEstado(boolean estado) {
       this.estado = estado;
   }
   public Set getDocentes() {
       return this.docentes;
   }
   
   public void setDocentes(Set docentes) {
       this.docentes = docentes;
   }
   public Set getCompetenciaesps() {
       return this.competenciaesps;
   }
   
   public void setCompetenciaesps(Set competenciaesps) {
       this.competenciaesps = competenciaesps;
   }
   public Set getPerfilprofs() {
       return this.perfilprofs;
   }
   
   public void setPerfilprofs(Set perfilprofs) {
       this.perfilprofs = perfilprofs;
   }
   public Set getPuaVersions() {
       return this.puaVersions;
   }
   
   public void setPuaVersions(Set puaVersions) {
       this.puaVersions = puaVersions;
   }
   public Set getSubcompetencias() {
       return this.subcompetencias;
   }
   
   public void setSubcompetencias(Set subcompetencias) {
       this.subcompetencias = subcompetencias;
   }
   public Set getEvaluacionCompetenciases() {
       return this.evaluacionCompetenciases;
   }
   
   public void setEvaluacionCompetenciases(Set evaluacionCompetenciases) {
       this.evaluacionCompetenciases = evaluacionCompetenciases;
   }
   public Set getPerfildocs() {
       return this.perfildocs;
   }
   
   public void setPerfildocs(Set perfildocs) {
       this.perfildocs = perfildocs;
   }
   public Set getEvaluacionFinals() {
       return this.evaluacionFinals;
   }
   
   public void setEvaluacionFinals(Set evaluacionFinals) {
       this.evaluacionFinals = evaluacionFinals;
   }
   public Set getPerfilacads() {
       return this.perfilacads;
   }
   
   public void setPerfilacads(Set perfilacads) {
       this.perfilacads = perfilacads;
   }
   public Set getCompetenciagens() {
       return this.competenciagens;
   }
   
   public void setCompetenciagens(Set competenciagens) {
       this.competenciagens = competenciagens;
   }

}
