package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * PuaVersion generated by hbm2java
 */
public class PuaVersion implements java.io.Serializable {

	private Integer id;
    private int version;
    private Pua pua;
    private byte[] pua_1;
    private String materia;
    private int planEstudio;

   public PuaVersion() {
   }

	
   public PuaVersion(Pua pua, String materia, int planEstudio) {
       this.pua = pua;
       this.materia = materia;
       this.planEstudio = planEstudio;
   }
   public PuaVersion(Pua pua, byte[] pua_1, String materia, int planEstudio) {
      this.pua = pua;
      this.pua_1 = pua_1;
      this.materia = materia;
      this.planEstudio = planEstudio;
   }
  
   public Integer getId() {
       return this.id;
   }
   
   public void setId(Integer id) {
       this.id = id;
   }
   public int getVersion() {
       return this.version;
   }
   
   public void setVersion(int version) {
       this.version = version;
   }
   public Pua getPua() {
       return this.pua;
   }
   
   public void setPua(Pua pua) {
       this.pua = pua;
   }
   public byte[] getPua_1() {
       return this.pua_1;
   }
   
   public void setPua_1(byte[] pua_1) {
       this.pua_1 = pua_1;
   }
   public String getMateria() {
       return this.materia;
   }
   
   public void setMateria(String materia) {
       this.materia = materia;
   }
   public int getPlanEstudio() {
       return this.planEstudio;
   }
   
   public void setPlanEstudio(int planEstudio) {
       this.planEstudio = planEstudio;
   }

}
