package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * SubcompetenciaMaterialId generated by hbm2java
 */
public class SubcompetenciaMaterialId implements java.io.Serializable {

	private Integer idSubcompetencia;
	private Integer idMaterial;

	public SubcompetenciaMaterialId() {
	}

	public SubcompetenciaMaterialId(Integer idSubcompetencia, Integer idMaterial) {
		this.idSubcompetencia = idSubcompetencia;
		this.idMaterial = idMaterial;
	}

	public Integer getIdSubcompetencia() {
		return this.idSubcompetencia;
	}

	public void setIdSubcompetencia(Integer idSubcompetencia) {
		this.idSubcompetencia = idSubcompetencia;
	}

	public Integer getIdMaterial() {
		return this.idMaterial;
	}

	public void setIdMaterial(Integer idMaterial) {
		this.idMaterial = idMaterial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubcompetenciaMaterialId))
			return false;
		SubcompetenciaMaterialId castOther = (SubcompetenciaMaterialId) other;

		return ((this.getIdSubcompetencia() == castOther.getIdSubcompetencia())
				|| (this.getIdSubcompetencia() != null && castOther.getIdSubcompetencia() != null
						&& this.getIdSubcompetencia().equals(castOther.getIdSubcompetencia())))
				&& ((this.getIdMaterial() == castOther.getIdMaterial())
						|| (this.getIdMaterial() != null && castOther.getIdMaterial() != null
								&& this.getIdMaterial().equals(castOther.getIdMaterial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSubcompetencia() == null ? 0 : this.getIdSubcompetencia().hashCode());
		result = 37 * result + (getIdMaterial() == null ? 0 : this.getIdMaterial().hashCode());
		return result;
	}

}
