package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subcompetencia generated by hbm2java
 */
public class Subcompetencia implements java.io.Serializable {

	private Integer idSubcompetencia;
	private Pua pua;
	private Integer numSubcompetencia;
	private String subcompetencia;
	private Integer sesiones;
	private Integer ponderacion;
	private Integer parcial;
	private Set bibliografiaSubcompetencias = new HashSet(0);
	private Set actividaddocs = new HashSet(0);
	private Set actividadals = new HashSet(0);
	private Set subcompetenciaAmbientes = new HashSet(0);
	private Set temas = new HashSet(0);
	private Set criterios = new HashSet(0);
	private Set evidenciaSubcompetencias = new HashSet(0);
	private Set subcompetenciaMaterials = new HashSet(0);

	public Subcompetencia() {
	}

	public Subcompetencia(Pua pua, Integer numSubcompetencia, String subcompetencia, Integer sesiones,
			Integer ponderacion, Integer parcial, Set bibliografiaSubcompetencias, Set actividaddocs, Set actividadals,
			Set subcompetenciaAmbientes, Set temas, Set criterios, Set evidenciaSubcompetencias,
			Set subcompetenciaMaterials) {
		this.pua = pua;
		this.numSubcompetencia = numSubcompetencia;
		this.subcompetencia = subcompetencia;
		this.sesiones = sesiones;
		this.ponderacion = ponderacion;
		this.parcial = parcial;
		this.bibliografiaSubcompetencias = bibliografiaSubcompetencias;
		this.actividaddocs = actividaddocs;
		this.actividadals = actividadals;
		this.subcompetenciaAmbientes = subcompetenciaAmbientes;
		this.temas = temas;
		this.criterios = criterios;
		this.evidenciaSubcompetencias = evidenciaSubcompetencias;
		this.subcompetenciaMaterials = subcompetenciaMaterials;
	}

	public Integer getIdSubcompetencia() {
		return this.idSubcompetencia;
	}

	public void setIdSubcompetencia(Integer idSubcompetencia) {
		this.idSubcompetencia = idSubcompetencia;
	}

	public Pua getPua() {
		return this.pua;
	}

	public void setPua(Pua pua) {
		this.pua = pua;
	}

	public Integer getNumSubcompetencia() {
		return this.numSubcompetencia;
	}

	public void setNumSubcompetencia(Integer numSubcompetencia) {
		this.numSubcompetencia = numSubcompetencia;
	}

	public String getSubcompetencia() {
		return this.subcompetencia;
	}

	public void setSubcompetencia(String subcompetencia) {
		this.subcompetencia = subcompetencia;
	}

	public Integer getSesiones() {
		return this.sesiones;
	}

	public void setSesiones(Integer sesiones) {
		this.sesiones = sesiones;
	}

	public Integer getPonderacion() {
		return this.ponderacion;
	}

	public void setPonderacion(Integer ponderacion) {
		this.ponderacion = ponderacion;
	}

	public Integer getParcial() {
		return this.parcial;
	}

	public void setParcial(Integer parcial) {
		this.parcial = parcial;
	}

	public Set getBibliografiaSubcompetencias() {
		return this.bibliografiaSubcompetencias;
	}

	public void setBibliografiaSubcompetencias(Set bibliografiaSubcompetencias) {
		this.bibliografiaSubcompetencias = bibliografiaSubcompetencias;
	}

	public Set getActividaddocs() {
		return this.actividaddocs;
	}

	public void setActividaddocs(Set actividaddocs) {
		this.actividaddocs = actividaddocs;
	}

	public Set getActividadals() {
		return this.actividadals;
	}

	public void setActividadals(Set actividadals) {
		this.actividadals = actividadals;
	}

	public Set getSubcompetenciaAmbientes() {
		return this.subcompetenciaAmbientes;
	}

	public void setSubcompetenciaAmbientes(Set subcompetenciaAmbientes) {
		this.subcompetenciaAmbientes = subcompetenciaAmbientes;
	}

	public Set getTemas() {
		return this.temas;
	}

	public void setTemas(Set temas) {
		this.temas = temas;
	}

	public Set getCriterios() {
		return this.criterios;
	}

	public void setCriterios(Set criterios) {
		this.criterios = criterios;
	}

	public Set getEvidenciaSubcompetencias() {
		return this.evidenciaSubcompetencias;
	}

	public void setEvidenciaSubcompetencias(Set evidenciaSubcompetencias) {
		this.evidenciaSubcompetencias = evidenciaSubcompetencias;
	}

	public Set getSubcompetenciaMaterials() {
		return this.subcompetenciaMaterials;
	}

	public void setSubcompetenciaMaterials(Set subcompetenciaMaterials) {
		this.subcompetenciaMaterials = subcompetenciaMaterials;
	}

}
