package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * SubcompetenciaAmbiente generated by hbm2java
 */
public class SubcompetenciaAmbiente implements java.io.Serializable {

	private SubcompetenciaAmbienteId id;
	private Ambiente ambiente;
	private Subcompetencia subcompetencia;

	public SubcompetenciaAmbiente() {
	}

	public SubcompetenciaAmbiente(SubcompetenciaAmbienteId id) {
		this.id = id;
	}

	public SubcompetenciaAmbiente(SubcompetenciaAmbienteId id, Ambiente ambiente, Subcompetencia subcompetencia) {
		this.id = id;
		this.ambiente = ambiente;
		this.subcompetencia = subcompetencia;
	}

	public SubcompetenciaAmbienteId getId() {
		return this.id;
	}

	public void setId(SubcompetenciaAmbienteId id) {
		this.id = id;
	}

	public Ambiente getAmbiente() {
		return this.ambiente;
	}

	public void setAmbiente(Ambiente ambiente) {
		this.ambiente = ambiente;
	}

	public Subcompetencia getSubcompetencia() {
		return this.subcompetencia;
	}

	public void setSubcompetencia(Subcompetencia subcompetencia) {
		this.subcompetencia = subcompetencia;
	}

}
