package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * SubcompetenciaAmbienteId generated by hbm2java
 */
public class SubcompetenciaAmbienteId implements java.io.Serializable {

	private Integer idSubcompetencia;
	private Integer idAmbiente;

	public SubcompetenciaAmbienteId() {
	}

	public SubcompetenciaAmbienteId(Integer idSubcompetencia, Integer idAmbiente) {
		this.idSubcompetencia = idSubcompetencia;
		this.idAmbiente = idAmbiente;
	}

	public Integer getIdSubcompetencia() {
		return this.idSubcompetencia;
	}

	public void setIdSubcompetencia(Integer idSubcompetencia) {
		this.idSubcompetencia = idSubcompetencia;
	}

	public Integer getIdAmbiente() {
		return this.idAmbiente;
	}

	public void setIdAmbiente(Integer idAmbiente) {
		this.idAmbiente = idAmbiente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubcompetenciaAmbienteId))
			return false;
		SubcompetenciaAmbienteId castOther = (SubcompetenciaAmbienteId) other;

		return ((this.getIdSubcompetencia() == castOther.getIdSubcompetencia())
				|| (this.getIdSubcompetencia() != null && castOther.getIdSubcompetencia() != null
						&& this.getIdSubcompetencia().equals(castOther.getIdSubcompetencia())))
				&& ((this.getIdAmbiente() == castOther.getIdAmbiente())
						|| (this.getIdAmbiente() != null && castOther.getIdAmbiente() != null
								&& this.getIdAmbiente().equals(castOther.getIdAmbiente())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSubcompetencia() == null ? 0 : this.getIdSubcompetencia().hashCode());
		result = 37 * result + (getIdAmbiente() == null ? 0 : this.getIdAmbiente().hashCode());
		return result;
	}

}
