package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * SubcompetenciaMaterial generated by hbm2java
 */
public class SubcompetenciaMaterial implements java.io.Serializable {

	private SubcompetenciaMaterialId id;
	private Material material;
	private Subcompetencia subcompetencia;

	public SubcompetenciaMaterial() {
	}

	public SubcompetenciaMaterial(SubcompetenciaMaterialId id) {
		this.id = id;
	}

	public SubcompetenciaMaterial(SubcompetenciaMaterialId id, Material material, Subcompetencia subcompetencia) {
		this.id = id;
		this.material = material;
		this.subcompetencia = subcompetencia;
	}

	public SubcompetenciaMaterialId getId() {
		return this.id;
	}

	public void setId(SubcompetenciaMaterialId id) {
		this.id = id;
	}

	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	public Subcompetencia getSubcompetencia() {
		return this.subcompetencia;
	}

	public void setSubcompetencia(Subcompetencia subcompetencia) {
		this.subcompetencia = subcompetencia;
	}

}
