package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Subtema generated by hbm2java
 */
public class Subtema implements java.io.Serializable {

	private Integer idSubtema;
	private Tema tema;
	private String subtemas;
	private Integer numeroSubtemas;

	public Subtema() {
	}

	public Subtema(Tema tema, String subtemas, Integer numeroSubtemas) {
		this.tema = tema;
		this.subtemas = subtemas;
		this.numeroSubtemas = numeroSubtemas;
	}

	public Integer getIdSubtema() {
		return this.idSubtema;
	}

	public void setIdSubtema(Integer idSubtema) {
		this.idSubtema = idSubtema;
	}

	public Tema getTema() {
		return this.tema;
	}

	public void setTema(Tema tema) {
		this.tema = tema;
	}

	public String getSubtemas() {
		return this.subtemas;
	}

	public void setSubtemas(String subtemas) {
		this.subtemas = subtemas;
	}

	public Integer getNumeroSubtemas() {
		return this.numeroSubtemas;
	}

	public void setNumeroSubtemas(Integer numeroSubtemas) {
		this.numeroSubtemas = numeroSubtemas;
	}

}
