package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipobib generated by hbm2java
 */
public class Tipobib implements java.io.Serializable {

	private Integer idTipoBibliografia;
	private String tipo;
	private Set bibliografiaPuas = new HashSet(0);

	public Tipobib() {
	}

	public Tipobib(String tipo, Set bibliografiaPuas) {
		this.tipo = tipo;
		this.bibliografiaPuas = bibliografiaPuas;
	}

	public Integer getIdTipoBibliografia() {
		return this.idTipoBibliografia;
	}

	public void setIdTipoBibliografia(Integer idTipoBibliografia) {
		this.idTipoBibliografia = idTipoBibliografia;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getBibliografiaPuas() {
		return this.bibliografiaPuas;
	}

	public void setBibliografiaPuas(Set bibliografiaPuas) {
		this.bibliografiaPuas = bibliografiaPuas;
	}

}
