package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipom generated by hbm2java
 */
public class Tipom implements java.io.Serializable {

	private Integer idTipo;
	private String tipo;
	private Set materias = new HashSet(0);

	public Tipom() {
	}

	public Tipom(String tipo, Set materias) {
		this.tipo = tipo;
		this.materias = materias;
	}

	public Integer getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(Integer idTipo) {
		this.idTipo = idTipo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set materias) {
		this.materias = materias;
	}

}
