package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * Tipo generated by hbm2java
 */
public class Tipo implements java.io.Serializable {

	private Integer idTipo;
	private String tipo;

	public Tipo() {
	}

	public Tipo(String tipo) {
		this.tipo = tipo;
	}

	public Integer getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(Integer idTipo) {
		this.idTipo = idTipo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
