package pua.hibernate;
// Generated 22/04/2019 09:38:09 PM by Hibernate Tools 4.3.1.Final

/**
 * TipoDocente generated by hbm2java
 */
public class TipoDocente implements java.io.Serializable {

	private Integer id;
	private int idTipo;
	private int idDocente;
	private Integer idFacultad;
	private Integer idCarrera;
	private Integer idAcademia;

	public TipoDocente() {
	}

	public TipoDocente(int idTipo, int idDocente) {
		this.idTipo = idTipo;
		this.idDocente = idDocente;
	}

	public TipoDocente(int idTipo, int idDocente, Integer idFacultad, Integer idCarrera, Integer idAcademia) {
		this.idTipo = idTipo;
		this.idDocente = idDocente;
		this.idFacultad = idFacultad;
		this.idCarrera = idCarrera;
		this.idAcademia = idAcademia;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(int idTipo) {
		this.idTipo = idTipo;
	}

	public int getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(int idDocente) {
		this.idDocente = idDocente;
	}

	public Integer getIdFacultad() {
		return this.idFacultad;
	}

	public void setIdFacultad(Integer idFacultad) {
		this.idFacultad = idFacultad;
	}

	public Integer getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(Integer idCarrera) {
		this.idCarrera = idCarrera;
	}

	public Integer getIdAcademia() {
		return this.idAcademia;
	}

	public void setIdAcademia(Integer idAcademia) {
		this.idAcademia = idAcademia;
	}

}
